dependencies:
  - python=3.8.8
  - pip:
      - azureml-defaults
      - azureml-sdk
      - pandas==1.1.3
      - numpy==1.19.2
      - scikit-learn
      - xgboost==1.1.1
      - bayesian-optimization
      - joblib
      - python-dotenv
      - azureml-monitoring
      - findspark
      - pyspark
      - pickle5
      - azure-ml-api-sdk
      - azureml-opendatasets
      - azureml-widgets

